// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPqPaYYuev92_TZw8pAcCmGqqHxtV7bZ8',
    appId: '1:661450372701:web:5ee050cfbd7d70666a3fb4',
    messagingSenderId: '661450372701',
    projectId: 'legal-log',
    authDomain: 'legal-log.firebaseapp.com',
    storageBucket: 'legal-log.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ27SuFi-WYfUdzxL_rPXeBKbtrewd1tA',
    appId: '1:661450372701:android:fa58888bec3eaa4b6a3fb4',
    messagingSenderId: '661450372701',
    projectId: 'legal-log',
    storageBucket: 'legal-log.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDpnsILW8miXQEpX7M5qx27V4nHW1wr3M',
    appId: '1:661450372701:ios:039940a4382999f16a3fb4',
    messagingSenderId: '661450372701',
    projectId: 'legal-log',
    storageBucket: 'legal-log.firebasestorage.app',
    iosBundleId: 'com.example.legalLog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDpnsILW8miXQEpX7M5qx27V4nHW1wr3M',
    appId: '1:661450372701:ios:039940a4382999f16a3fb4',
    messagingSenderId: '661450372701',
    projectId: 'legal-log',
    storageBucket: 'legal-log.firebasestorage.app',
    iosBundleId: 'com.example.legalLog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPqPaYYuev92_TZw8pAcCmGqqHxtV7bZ8',
    appId: '1:661450372701:web:da8ed5f730b4d9676a3fb4',
    messagingSenderId: '661450372701',
    projectId: 'legal-log',
    authDomain: 'legal-log.firebaseapp.com',
    storageBucket: 'legal-log.firebasestorage.app',
  );
}
